trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_SUBSCRIPTION_ID: '3e1292a5-5ba2-445a-a910-d10a68561a8b'
  ARM_CLIENT_ID: '<service-principal-client-id>'
  ARM_CLIENT_SECRET: '<service-principal-secret>'
  ARM_TENANT_ID: '<tenant-id>'

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.0'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'