steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
    curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
    unzip terraform_1.5.0_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

- script: |
    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
    export ARM_TENANT_ID=$(ARM_TENANT_ID)
    export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)

    terraform init
  displayName: 'Terraform Init'

- script: |
    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
    export ARM_TENANT_ID=$(ARM_TENANT_ID)
    export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)

    terraform plan
  displayName: 'Terraform Plan'

- script: |
    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
    export ARM_TENANT_ID=$(ARM_TENANT_ID)
    export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)

    terraform apply -auto-approve
  displayName: 'Terraform Apply'