trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
    curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
    unzip terraform_1.5.0_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'